import Head from 'next/head';

import Search from '../components/Search.js';
import Layout from '../components/Layout.js';

import { supabase } from '../lib/initSupabase';

// export async function getServerSideProps({ req, res }) {
//   const { data, error } = await supabase.from('Videos').select('*');
//   return {
//     props: {
//       data: data,
//       dataError: error,
//     },
//   };
// }

// export async function getServerSideProps({ req, res }) {
//   return fetch(url)
//     .then((response) => response.json())
//     .then((data) => {
//       return {
//         props: {
//           videoList: data,
//         },
//       };
//     });
// }

export default function Home() {
  return (
    <div>
      <Head>
        <title>FAC-Tube</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="apple-touch-icon"
          sizes="180x180"
          href="/apple-touch-icon.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="/favicon-32x32.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="/favicon-16x16.png"
        />
        <link rel="manifest" href="/site.webmanifest" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@1,700&display=swap"
          rel="stylesheet"
        />
      </Head>
      <Layout>
        <main>
          <Search />
        </main>
      </Layout>
    </div>
  );
}
