import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import React from 'react';
import ReactPlayer from 'react-player';

import { supabase } from '../lib/initSupabase';

// export async function getServerSideProps({ req, res }) {
//   const { data, error } = await supabase.from('Videos').select('*');
//   return {
//     props: {
//       data: data,
//       dataError: error,
//     },
//   };
// }

// const url = `https://www.googleapis.com/youtube/v3/search?part=snippet&maxResults=25&q=${searchTerm}&key=${YOUTUBE_API_KEY}`;
const YOUTUBE_API_KEY = 'AIzaSyANi3rDROII6mQHbTvPq4jMQ77adAVX1kA';
const searchTerm = 'html';
const url = `https://www.googleapis.com/youtube/v3/search?part=snippet&maxResults=25&q=${searchTerm}&key=${YOUTUBE_API_KEY}`;

// fetch(url)
//   .then((response) => response.json())
//   .then((data) => {
//     console.log(`https://www.youtube.com/embed/${data.items[0].id.videoId}`);
//   });
export async function getServerSideProps({ req, res }) {
  return fetch(url)
    .then((response) => response.json())
    .then((data) => {
      // console.log(data);
      // const { data, error } = await
      return {
        props: {
          videoList: data,
        },
      };
    });
}

export default function Home({ videoList }) {
  console.log(videoList);
  const listArr = videoList.items;
  return (
    <div className={styles.container}>
      <Head>
        <title>FAC-Tube</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>here are some videos</h1>

        <div className="video-list">
          {listArr.map((video) => (
            <div className="video-card" key={`${video.id.videoId}`}>
              <p>{video.snippet.title}</p>
              <h3>{video.snippet.channelTitle}</h3>
              <p>{video.snippet.description}</p>
              <ReactPlayer
                controls="true"
                url={`https://www.youtube.com/watch?v=${video.id.videoId}`}
              />
            </div>
          ))}
        </div>
      </main>
    </div>
  );
}
