import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';

import { supabase } from '../lib/initSupabase';

// export async function getServerSideProps({ req, res }) {
//   const { data, error } = await supabase.from('Videos').select('*');
//   return {
//     props: {
//       data: data,
//       dataError: error,
//     },
//   };
// }

// const YOUTUBE_API_KEY = process.env.YOUTUBE_API_KEY;
const searchTerm = 'html';
const url = `https://www.googleapis.com/youtube/v3/search?part=snippet&maxResults=25&q=${searchTerm}&key=${YOUTUBE_API_KEY}`;

export async function getServerSideProps({ req, res }) {
  return fetch(url)
    .then((response) => response.json())
    .then((data) => {
      // console.log(data);
      return {
        props: {
          videoList: data,
        },
      };
    });
}

export default function Home({ videoList }) {
  console.log(videoList);
  const listArr = videoList.items;
  return (
    <div className={styles.container}>
      <Head>
        <title>FAC-Tube</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="apple-touch-icon"
          sizes="180x180"
          href="/apple-touch-icon.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="/favicon-32x32.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="/favicon-16x16.png"
        />
        <link rel="manifest" href="/site.webmanifest" />
      </Head>
      <main>
        <h2>Here are some videos</h2>

        <div className="video-list">
          {listArr.map((video) => {
            if (video.id.videoId !== undefined) {
              return (
                <div className="video-card" key={video.id.videoId}>
                  <h3>{video.snippet.title}</h3>
                  <h4>{video.snippet.channelTitle}</h4>
                  <p>{video.snippet.description}</p>
                  <ReactPlayer
                    controls={true}
                    url={`https://www.youtube.com/watch?v=${video.id.videoId}`}
                  />
                </div>
              );
            }
          })}
        </div>
      </main>
    </div>
  );
}
